# -*- coding: utf-8 -*-
"""ConvertToTxt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1epL7sW6O7I-rvumEYJ3JsZpRG5AiC0M9

### Función para leer DOC y DOCX
"""

import win32com.client
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
from io import StringIO
import os



def doc_to_text(file):
    wb = app.Documents.Open(file)
    doc = app.ActiveDocument
    text = doc.Content.Text
    wb.Close()

    return text


"""### Función para leer PDF"""

def pdf_to_text(path):
    rsrcmgr = PDFResourceManager()
    retstr = StringIO()
    layout = LAParams()
    device = TextConverter(rsrcmgr, retstr, laparams=layout)
    filepath = open(path, 'rb')
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    password = ''
    maxpages = 0
    caching = True
    pagenos = set()

    for page in PDFPage.get_pages(filepath, pagenos, maxpages=maxpages, password=password, caching=caching,
                                  check_extractable=True):
        interpreter.process_page(page)

    text = retstr.getvalue()

    filepath.close()
    device.close()
    retstr.close()
    return text


"""### Función para leer todos los archivos desde una carpeta raiz"""



def getListOfFiles(dirName):
    # create a list of file and sub directories
    # names in the given directory
    files = os.listdir(dirName)
    allFiles = list()
    # Iterate over all the entries
    for file in files:
        # Create full path
        fullPath = dirName + "\\" + file
        # If entry is a directory then get the list of files in this directory
        if os.path.isdir(fullPath):
            allFiles = allFiles + getListOfFiles(fullPath)
        else:
            allFiles.append(fullPath)

    return allFiles


"""### Función para grabar un texto en un archivo TXT"""


def saveTxt(text, textFilename):
    textFile = open(textFilename, "w", encoding="utf-8")
    textFile.write(text)
    textFile.close()


"""### Genero todos los TXT"""

filesDir = r"C:\Users\azelaya004\PycharmProjects\Busqueda-y-Recomendacion-para-Textos-Legales-Mentoria-2022-main\Datos"
listOfFiles = getListOfFiles(filesDir)
print('Cantidad de archivos a importar:', len(listOfFiles))

app = win32com.client.Dispatch("Word.Application")

for file in listOfFiles:
    fileDestino = file.replace("\\Datos\\", "\\Documentos\\")
    print(file, "\n", "--->", fileDestino, "\n")

    if file.endswith(".doc") or file.endswith(".docx"):
        texto = doc_to_text(file)
        saveTxt(texto, fileDestino + ".txt")

    if file.endswith(".pdf"):
        texto = pdf_to_text(file)
        saveTxt(texto, fileDestino + ".txt")

app.Quit()

